config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#index'

  get '/about', to: 'about#index'
  get '/contact', to: 'contact#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def new
    @post = Post.new
  end

  def index
    @posts = Post.last(12)
    @post = Post.new
    @featured_post = Post.last
    # @your_post = want this to be your last post
  end

  def create
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit([:title, :body])
  end

  def find_post
    @post = Post.find params[:id]
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!-- User welcome dashboard -->
<div class="">
  <% if user_signed_in? %>
    <h1>Welcome <%= current_user.username %></h1>
  <% else %>
    <h1>Dashboard</h1>
  <% end %>
  <hr />
</div>


<div class="login-box">
  <% if user_signed_in? %>
  <div class="col-md-6">
    <div class="well">

      <div class="row">
        <div class="col-sm-4">
          <img class="img_icon" src="http://cagewheel.com/images/thumb1.png" alt="">
        </div>

        <div class="col-sm-8">
          <%= link_to 'Edit Profile', edit_user_path(current_user), class:'pull-right' %>
          <h2><%= current_user.username %> </h2>
          <p><strong>First name: </strong>first</p>
          <p><strong>Last name: </strong>Last</p>
          <p><strong>Location: </strong>Vancouver</p>
          <p><strong>Karma: </strong>2134</p>
          <p><strong>Posts: </strong>532</p>
          <hr />
        </div>
        <div class="container-fluid">

          <p><strong>Bio: </strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        </div>

    </div>
  </div>
</div>

<!-- featured post on page -->
<div class="col-md-6">
  <div class="well">
    <h2>Your Top Post</h2>
    <hr />
    <h2><%= link_to @featured_post.title, post_path(@featured_post) %></h1>
    <p><%= @featured_post.body %></p>
  </div>
</div>

<!-- if not logged in -->
<% else %>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        <h3>Please sign in first</h3>
      <%= form_tag sessions_path do %>
      <div class="">
        <%= email_field_tag :email, nil, placeholder: "Email address", :class => "form-control" %>
      </div>
      <div class="">
        <%= password_field_tag :password, nil, placeholder: "Password", :class => "form-control" %>
      </div>
      <br>
      <%= submit_tag "Login", :class => "btn btn-lg btn-primary btn-block" %>
      <div class="checkbox">
        <%= link_to 'Forgot Password?', new_password_reset_path, :class => "pull-right" %>
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>

      <h4> <%= link_to 'Sign up here', new_user_path %></h4>
      <% end %>
    </div>
  </div>
  </div>
  <% end %>
</div>