config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#index'

  get '/about', to: 'about#index'
  get '/contact', to: 'contact#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :nullify
  belongs_to :user

  validates(:title, { presence: { message: 'must be present!' }})
  validates(:body, { presence: true, length: { minimum: 5 } })
end

app/models/posts.rb
class Posts < ApplicationRecord
  has_many :comments, dependent: :nullify
  belongs_to :user

  validates(:title, { presence: { message: 'must be present!' }})
  validates(:body, { presence: true, length: { minimum: 5 } })
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.last(12)
    @post = Post.new
    @featured_post = Post.first
  end

  def show
    @post = Post.find(params[:id])
    @users = User.all
    @comment = Comment.new
    @comments = Comment.all
  end

  def new
    redirect_to root_path, alert: 'Access denied!' unless can? :edit, @post
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
      # redirect_to :index
    else
      render :new
    end
  end

  def edit
    redirect_to root_path, alert: 'Access denied!' unless can? :edit, @post
  end

  def update
    if !(can? :edit, @post)
      redirect_to root_path, alert: 'Access denied'
    elsif @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated'
    else
    render :edit
    end
  end


  def destroy
    if can? :destroy, @post
      @post.destroy
      redirect_to post_index_path, notice: 'Post Deleted'
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  private

    def post_params
      params.require(:post).permit([:title, :body])
    end

    def find_post
      @post = Post.find params[:id]
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.last(12)
    @post = Post.new
    @featured_post = Post.last
  end

  def show
    @post = Post.find(params[:id])
    @users = User.all
    @comment = Comment.new
    @comments = Comment.all
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params.require(:post).permit([:title, :body, :post_id])
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post), notice: 'Post successful'
    else
      render :new
    end
  end

  def edit
    redirect_to root_path, alert: 'Access denied!' unless can? :edit, @post
  end

  def update
    if !(can? :edit, @post)
      redirect_to  post_path(@post), alert: 'Access denied'
    elsif @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated'
    else
    render :edit
    end
  end


  def destroy
    if can? :destroy, @post
      @post.destroy
      redirect_to posts_path, notice: 'Post Deleted'
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  private

    def post_params
      params.require(:post).permit([:title, :body])
    end

    def find_post
      @post = Post.find params[:id]
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.present? %>
  <%= @post.errors.full_messages.join(', ') %>
<% end %>

<div class="col-md-8">
  <%= form_for @post do |f| %>
      <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <br />
      <label class="btn btn-default btn-file">
        <input type="file" hidden>
      </label>
      <%= f.submit :submit, class: "pull-right btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<!-- post index page -->

<div class="">
  <%= link_to 'New Blog Post', new_post_path(@post), :class => "btn btn-lg btn-primary pull-right"  %>
  <h1>Blogz <small>The best blogsite NA</small></h1>
  <% if user_signed_in? %>
    <h4>Welcome, <%= current_user.username %> </h4>
  <% end %>

  <hr>
</div>

<!-- featured post -->
<div class="container-fluid hidden-sm hidden-xs">
  <div class="row">
    <div class="col-md-8">

      <div class="featured_post">
        <img class="img_post" src="http://i2.cdn.turner.com/money/dam/assets/151222154733-nicolas-cage-nyc-780x439.jpg" alt="">
      </div>
      <div class="img_social">
        <a href="#"><i class="fa fa-heart-o fa-2x" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-comment-o fa-2x" aria-hidden="true"></i></a>
        <a href="#" class="pull-right"><i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i></a>
      </div>
      <p class='pull-right'>Post by: <%= @featured_post.user.username %></p>
      <h1><%= link_to @featured_post.title, post_path(@featured_post) %></h1>

      <p><%= @featured_post.body %></p>

    </div>

<!-- sidepost -->
    <div class="col-md-4">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Nicolas Cage Speaks Against Fibonacci</h5>
            <small>1 hour ago</small>
          </div>
          <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Tips for BBQ Season</h5>
              <small class="text-muted">2 hours ago</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Illuminati exposed</h5>
              <small class="text-muted">2 hours ago</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Obama Still Cares</h5>
              <small class="text-muted">48 min ago</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
        </div>
      </div>

    </div>
    <hr>
  </div>  <!-- end of hidden on sm  -->

<!-- all posts list -->
    <% @posts.each_slice(3) do |rows|  %>
      <div class="row">
        <% rows.each do |post|  %>
          <div class="col-sm-4">
            <div class="img_container">
              <img class="img_post" src="https://s3.drafthouse.com/images/made/12439707_9414869_pm_758_426_81_s_c1.jpg" alt="">
              <div class="img_social">
                <a href="#"><i class="fa fa-heart-o fa-2x" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-comment-o fa-2x" aria-hidden="true"></i></a>
                <a href="#" class="pull-right"><i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i></a>
              </div>
            </div>
            <small class='pull-right'>Posted by:
              <%= post.user.username %>
            </small>
            <h2><%= link_to post.title, post_path(post) %></h2>
            <p><%= post.body %></p>
          </div>
        <% end %>
      </div>
    <% end %>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>
<hr />

<%= render 'form' %>

app/views/posts/show.html.erb
<!-- <h1>show page</h1> -->
<div class="row">
  <div class="col-md-7">

<!-- ownership edit/delete -->
    <% if can? :edit, @post %>
      <div class="pull-right">
        <br>
        <%= link_to 'Edit', edit_post_path(@post), :class => "btn btn-primary"  %>
        <%= link_to 'Delete', post_path(@post), :class => "btn btn-primary",
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

<!-- show post -->
    <h1><%= @post.title %></h1>
    <p>Post by: <%= @post.user.username %></p>
    <hr />

    <div class="img_container">
      <img class="img_post" src="https://s3.drafthouse.com/images/made/12439707_9414869_pm_758_426_81_s_c1.jpg" alt="">
      <a href="#"><i class="fa fa-heart-o fa-2x pad-left" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-comment-o fa-2x pad-left" aria-hidden="true"></i></a>
      <a href="#" class="pull-right pad-right"><i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i></a>
    </div>
    <p><%= @post.body %></p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>


<!-- comments -->
  <div class="col-md-5">
    <h1 class="">Comments</h1>
    <hr />
    <br />

    <div class="">
      <%= @comment.errors.full_messages.join(', ') %>

      <% if user_signed_in? %>
      <p>Posting as: <strong><%= current_user.username %></strong></p>
      <% end %>
      <%= form_for [@post, @comment] do |f| %>
      <div class="form-group">
        <%= f.text_area :body, class: "form-control" %>
        <br>

        <%= f.submit :Submit, class: "pull-right btn btn-primary"  %>
      </div>
      <% end %>
    </div>
    <br>
<hr>
<!-- generate comments -->
<div class="container-fluid">

    <% @post.comments.each do |comment| %>
      <p class="text-muted pull-right">Posted on: Jan 23 2016</p>
      <p class=""><strong><%= comment.user.username %></strong></p>
      <p><%= comment.body %></p>

  <% if can? :destroy, comment %>
  <!-- link_to('Delete', [@post, @comment], -->
      <%= link_to('Delete', post_comment_path(@post, comment),
        method: :delete,
        data: {confirm: "Are you sure?"})%>
    <% else %>
    <% end %>
    <hr />
    <% end %>
  </div>

  </div>
</div>