config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#index'

  get '/about', to: 'about#index'
  get '/contact', to: 'contact#index'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :create]
  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

    if user.is_admin?
      can :manage, :all
    end

    can [:edit, :destroy], Post do |post|
      post.user == user
    end

    can [:edit, :destroy], Comment do |comment|
      comment.user == user
    end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :nullify
  belongs_to :user

  validates(:title, { presence: { message: 'must be present!' }})
  validates(:body, { presence: true, length: { minimum: 5 } })
end

app/models/posts.rb
class Posts < ApplicationRecord
  has_many :comments, dependent: :nullify
  belongs_to :user

  validates(:title, { presence: { message: 'must be present!' }})
  validates(:body, { presence: true, length: { minimum: 5 } })
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify

  validates(:username, { presence: true, uniqueness: true })
  validates(:first_name, presence: true)
  validates(:last_name, presence: true)

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    format: VALID_EMAIL_REGEX

  before_validation :downcase_email

  def self.search(search_term)
    where(['username ILIKE ? OR email ILIKE ?', "%#{search_term}%", "%#{search_term}%"])
  end

  def self.created_after(date)
    where(['created_at > ?', "#{date}"])
  end

  def self.is_not(name)
    where('username != ? AND email != ?', "#{name}", "#{name}")
  end

  private

  def downcase_email
    self.email.downcase! if email.present?
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end 
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.last(12)
    @post = Post.new
    @featured_post = Post.first
  end

  def show
    @post = Post.find(params[:id])
    @users = User.all
    @comment = Comment.new
    @comments = Comment.all
  end

  def new
    redirect_to root_path, alert: 'Access denied!' unless can? :edit, @post
  end

  def create
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
      # redirect_to :index
    else
      render :new
    end
  end

  def edit
    redirect_to root_path, alert: 'Access denied!' unless can? :edit, @post
  end

  def update
    if !(can? :edit, @post)
      redirect_to root_path, alert: 'Access denied'
    elsif @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated'
    else
    render :edit
    end
  end


  def destroy
    if can? :destroy, @post
      @post.destroy
      redirect_to post_index_path, notice: 'Post Deleted'
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  private

    def post_params
      params.require(:post).permit([:title, :body])
    end

    def find_post
      @post = Post.find params[:id]
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.last(12)
    @post = Post.new
    @featured_post = Post.last
  end

  def show
    @post = Post.find(params[:id])
    @users = User.all
    @comment = Comment.new
    @comments = Comment.all
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params.require(:post).permit([:title, :body, :post_id])
    @post = Post.new post_params
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post), notice: 'Post successful'
    else
      render :new
    end
  end

  def edit
    redirect_to root_path, alert: 'Access denied!' unless can? :edit, @post
  end

  def update
    if !(can? :edit, @post)
      redirect_to  post_path(@post), alert: 'Access denied'
    elsif @post.update(post_params)
      redirect_to post_path(@post), notice: 'Post updated'
    else
    render :edit
    end
  end


  def destroy
    if can? :destroy, @post
      @post.destroy
      redirect_to posts_path, notice: 'Post Deleted'
    else
      redirect_to root_path, alert: 'Access denied'
    end
  end

  private

    def post_params
      params.require(:post).permit([:title, :body])
    end

    def find_post
      @post = Post.find params[:id]
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # before_action :authenticate_user!
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User created and signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong!!"
      render :new
    end
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def new
    @post = Post.new
  end

  def index
    @posts = Post.last(12)
    @post = Post.new
    @featured_post = Post.last
    # @your_post = want this to be your last post
  end

  def create
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit([:title, :body])
  end

  def find_post
    @post = Post.find params[:id]
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog/index.html.erb
<div class="">

  <%= link_to 'New Blog Post', new_blog_path(@post), :class => "btn btn-lg btn-primary pull-right"  %>
  <h1>Blogz</h1>
  The best blogsite NA
  <hr>
</div>


<div class="container-fluid hidden-sm hidden-xs">
  <div class="row">
    <div class="col-md-8">

      <div class="featured_post">
        <img class="img_post" src="http://i2.cdn.turner.com/money/dam/assets/151222154733-nicolas-cage-nyc-780x439.jpg" alt="">
      </div>
      <div class="img_social">
        <a href="#"><i class="fa fa-heart-o fa-2x" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-comment-o fa-2x" aria-hidden="true"></i></a>
        <a href="#" class="pull-right"><i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i></a>
      </div>
      <h1><%= link_to @featured_post.title %></h1>
      <!-- , post_path(post) -->
      <p><%= @featured_post.body %></p>

    </div>

<!-- sidepost -->
    <div class="col-md-4">
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Nicolas Cage Speaks Against Fibonacci</h5>
            <small>1 hour ago</small>
          </div>
          <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Tips for BBQ Season</h5>
              <small class="text-muted">2 hours ago</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Illuminati exposed</h5>
              <small class="text-muted">2 hours ago</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
          <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Obama Still Cares</h5>
              <small class="text-muted">48 min ago</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          </a>
        </div>
      </div>

    </div>
    <hr>
  </div>  <!-- end of hidden on sm  -->

    <% @posts.each_slice(3) do |triplets|  %>
      <div class="row">
        <% triplets.each do |post|  %>
          <div class="col-sm-4">
            <div class="img_container">
              <img class="img_post" src="https://s3.drafthouse.com/images/made/12439707_9414869_pm_758_426_81_s_c1.jpg" alt="">
              <div class="img_social">
                <a href="#"><i class="fa fa-heart-o fa-2x" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-comment-o fa-2x" aria-hidden="true"></i></a>
                <a href="#" class="pull-right"><i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i></a>
              </div>
            </div>
            <h2><%= link_to post.title, blog_path(post) %></h2>
            <p><%= post.body %></p>
          </div>
        <% end %>
      </div>
    <% end %>

app/views/blog/show.html.erb
<!-- <h1>show page</h1> -->
<div class="row">
  <div class="col-md-7">
    <h1><%= @post.title %></h1>
<hr />

  <div class="img_container">
    <img class="img_post" src="https://s3.drafthouse.com/images/made/12439707_9414869_pm_758_426_81_s_c1.jpg" alt="">
    <a href="#"><i class="fa fa-heart-o fa-2x pad-left" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-comment-o fa-2x pad-left" aria-hidden="true"></i></a>
    <a href="#" class="pull-right pad-right"><i class="fa fa-bookmark-o fa-2x" aria-hidden="true"></i></a>
  </div>
  <p><%= @post.body %></p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
  <div class="col-md-5">
    <h1 class="">Comments</h1>
<hr /><br />

    <%= @comment.errors.full_messages.join(', ') %>
    <%# action=/questions/:question_id/answers %>
    <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body %>
    <%= f.submit %>
    <% end %>

    <% @post.comments.each do |comment| %>
    <p class="text-muted pull-right">Posted on: Jan 23 2016</p>
    <p class=""><strong>Username</strong></p>

      <%#= comment.username %>
    <p><%= comment.body %></p>

    <%#= link_to(
     'Delete', question_answer_path(@question, answer), method: :delete,
     data: {confirm: "Are you sure?"}
     )%>
    <hr />
    <% end %>


  </div>

</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">

  <div class="panel-footer text-center">
    Blogz 2017 &copy; | 

    <a href="#">
      <i class="fa fa-facebook-square" aria-hidden="true"></i>Facebook</a> |
    <a href="#">
      <i class="fa fa-github" aria-hidden="true"></i>Github</a> |
    <a href="#">
      <i class="fa fa-stack-overflow" aria-hidden="true"></i>Stack</a> |
    <a href="#">
      <i class="fa fa-linkedin" aria-hidden="true"></i>LinkedIn</a>

  </div>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header container-fluid">
      <a class="navbar-btn" href="/"></a>

      <button type="button" class="navbar-toggle collapsed nav-title" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a href="/">
        <img id="navlogo" class="navbar-brand" src="https://blog.vararu.org/content/images/2014/May/logo-main-grey-2x.png" alt="">
      </a>
      <%= link_to 'Blogz Feed', posts_path, class: 'navbar-brand' %>

    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Dashboard', root_path %></li>

        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to 'About', about_path %></li>
        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to 'Contact', contact_path %></li>

        <li class="navbar-form pull-right hidden-md-down">
          <%= form_tag("/search", :method => "get") do %>
             <%= text_field_tag :search, nil, placeholder: "Search", :class => "form-control" %>
           <% end %>
         </li>

      <% if user_signed_in? %>

        <li><%= link_to 'Logout', sessions_path, method: :delete, data: {confirm: 'Logout?'} %> </li>
        <% else %>
        <li><%= link_to 'Sign Up', new_user_path %> </li>
        <li><%= link_to 'Login', new_session_path %> </li>
      <% end %>
      </ul>
    </div>
</nav>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <div class="push"></div>
    <%= render 'layouts/footer' %>
  </body>
</html>